global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "biometric-agent"
    static_configs:
      - targets: ["biometric-agent:8000"]
    metrics_path: /metrics/
    scrape_interval: 10s
